version: '3'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/test

  redis:
    image: redis:latest
    ports:
      - "6379:6379"