import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/header/header";
import Footer from "./components/layout/footer/footer";
import Drawer from "./components/ui/drawer/Drawer";

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" type="image/svg+xml" href="/groove.svg" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Akeru</title>
        <meta name="description" content="AI for you" />
      </head>
      <body className={montserrat.variable}>
        <Drawer>
          <Header />
          {children}
          <Footer />
        </Drawer>
      </body>
    </html>
  );
}
