name: Deploy to DigitalOcean

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file
        run: |
          touch subnet/miner-cloudflare/.env
          echo SERVICE_MESH_SECRET_KEY=${{ secrets.SERVICE_MESH_SECRET_KEY }} >> ./subnet/miner-cloudflare/.env
          echo CLOUDFLARE_AUTH_TOKEN=${{ secrets.CLOUDFLARE_AUTH_TOKEN }} >> ./subnet/miner-cloudflare/.env
          echo CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} >> ./subnet/miner-cloudflare/.env
          echo MINER_ADDRESS=${{ secrets.MINER_ADDRESS }} >> ./subnet/miner-cloudflare/.env
          echo UUID=${{ secrets.CLOUDFLARE_MINER_TEST_ID }} >> ./subnet/miner-cloudflare/.env
          echo SERVICE_MESH_URL=${{ secrets.SERVICE_MESH_URL }} >> ./subnet/miner-cloudflare/.env
          echo API_ONLY=${{ secrets.CLOUDFLARE_MINER_API_ONLY }} >> ./subnet/miner-cloudflare/.env

      - name: Build Docker Image
        run: docker build -t cloudflare-miner ./subnet/miner-cloudflare/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Container Registry
        run: |
          IMAGE_TAG=ghcr.io/${{ github.repository }}/cloudflare-miner:${{ github.sha }}
          docker tag cloudflare-miner $IMAGE_TAG
          docker push $IMAGE_TAG
