name: "Integration Tests"
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # install bun
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v2
      - name: install dependencies
        run: bun install
      - name: integrtion tests
        run: bun run test:api:integration
