name: "Integration Tests"
on:
  pull_request_target:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # install bun
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v2
      - name: install dependencies
        run: bun install
      - name: integrtion tests
        env:
          NEO4J_PASSWORD: ${{ secrets.NEO4J_PASSWORD }}
          NEO4J_URI: ${{ secrets.NEO4J_URI }}
          NEO4J_USER: ${{ secrets.NEO4J_USER }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_SCHEME: ${{ secrets.REDIS_SCHEME }}
          REDIS_USER: ${{ secrets.REDIS_USER }}
        run: bun run test:api:integration
