name: "Integration Tests"
on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # install bun
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v2
      - name: install dependencies
        run: bun install
      # start docker containers
      - name: Start stack
        run: bun dev:containers
        # future commands for integrations tests
      - name: Run integration tests
        run: bun run test:integration
      - name: Tear down
        if: always()
        run: bun run dev:down
