name: "Install"
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # install bun
      - uses: oven-sh/setup-bun@v1
      - uses: actions/checkout@v2
      - name: bun version
        run: bun -v
      - name: install dependencies
        run: bun install
